In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
## Sentenses for example
sent=['the glass of milk',
      'the cup of tea',
      'I am a good boy',
      'I am a good developer',
      'understand the meaning of words',
      'your videos are good',]


In [4]:
## define the vocabulary size
voc_size=10000

In [5]:
## One hot representation
one_hot_rep=[one_hot(words,voc_size) for words in sent]
one_hot_rep


[[4866, 1920, 1849, 7988],
 [4866, 3518, 1849, 3789],
 [7126, 1518, 8901, 7616, 3914],
 [7126, 1518, 8901, 7616, 4185],
 [8411, 4866, 8396, 1849, 6848],
 [9716, 9797, 7517, 7616]]

In [20]:
## word embedding reprsentation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [21]:
sent_length=8
embedding_docs=pad_sequences(one_hot_rep,padding="pre",maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 4866 1920 1849 7988]
 [   0    0    0    0 4866 3518 1849 3789]
 [   0    0    0 7126 1518 8901 7616 3914]
 [   0    0    0 7126 1518 8901 7616 4185]
 [   0    0    0 8411 4866 8396 1849 6848]
 [   0    0    0    0 9716 9797 7517 7616]]


In [22]:
## feauture representation
dim=10

In [29]:
##model creation
model=Sequential()
model.add(Embedding(voc_size,dim,input_shape=(sent_length,)))
model.compile(optimizer='adam',loss='mse')


e:\GenAI LLM 2024\venv2\Lib\site-packages\keras\src\layers\core\embedding.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [30]:
print(model.summary())

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

None


In [31]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 707ms/step


array([[[-0.02849722, -0.04017762,  0.04042012, -0.00851816,
          0.03977049,  0.01120884,  0.00480028, -0.00259539,
         -0.03930696, -0.04447946],
        [-0.02849722, -0.04017762,  0.04042012, -0.00851816,
          0.03977049,  0.01120884,  0.00480028, -0.00259539,
         -0.03930696, -0.04447946],
        [-0.02849722, -0.04017762,  0.04042012, -0.00851816,
          0.03977049,  0.01120884,  0.00480028, -0.00259539,
         -0.03930696, -0.04447946],
        [-0.02849722, -0.04017762,  0.04042012, -0.00851816,
          0.03977049,  0.01120884,  0.00480028, -0.00259539,
         -0.03930696, -0.04447946],
        [ 0.03699693,  0.02292437,  0.03174673,  0.0136543 ,
         -0.03928083,  0.02047057,  0.04046539, -0.0364658 ,
         -0.0415206 ,  0.02480738],
        [-0.04621868,  0.03428674,  0.010554  ,  0.02085086,
         -0.01885692, -0.04255612,  0.00718749, -0.03390757,
         -0.01702683, -0.0449208 ],
        [ 0.0199613 ,  0.00352118,  0.03434534, -0.0